 import Header from "@/components/public/Header";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";


export const metadata = {
  title: "Fashi E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body>
    <Header/>
    {children}
      </body>
    </html>
  </ClerkProvider>
  );
}
