import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import "./globals.css";
import { AppSidebar } from "@/components/app-sidebar";
import { SiteHeader } from "@/components/site-header";
import { AuthProvider } from "@/components/service/auth-context";
import { Toaster } from "@/components/ui/toaster";

export const metadata = {
  title: "Fashi E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <AuthProvider>
          <Toaster
        position="top-right"
        richColors
        toastOptions={{
          classNames: {
            success: "bg-green-500 text-white border-green-600",
            error: "bg-red-500 text-white border-red-600",
            warning: "bg-yellow-500 text-white border-yellow-600",
            info: "bg-blue-500 text-white border-blue-600",
          },
        }}
      />
          <SidebarProvider className="flex flex-col min-h-screen">
            <SiteHeader />
            <div className="flex flex-1 overflow-hidden">
              <AppSidebar />
              <SidebarInset className="flex-1 overflow-y-auto">
                <main className="">
                  {children}
                </main>
              </SidebarInset>
            </div>
          </SidebarProvider>
        </AuthProvider>
      </body>
    </html>
  );
}